CREATE TABLE "DB2INST1"."CRM_ZM_ENUM_REF"  (
          "DICT_ID" VARCHAR(30) NOT NULL , 
          "DICT_NAME" VARCHAR(50) NOT NULL , 
          "DICT_KEY" VARCHAR(30) NOT NULL , 
          "DICT_VALUE" VARCHAR(50) , 
          "ZM_DICT_KEY" VARCHAR(30) NOT NULL , 
          "ZM_DICT_VALUE" VARCHAR(50) )   
         IN "TD_SALE"   ;
ALTER TABLE "DB2INST1"."CRM_ZM_ENUM_REF" 
    ADD PRIMARY KEY
        ("DICT_ID",
         "DICT_KEY",
         "ZM_DICT_KEY") ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ENUM_REF" TO USER "DB2INST1"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ENUM_REF" TO USER "DB2INST2"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ENUM_REF" TO USER "READER  "  ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ENUM_REF" TO USER "DB2INST1"  ;

CREATE TABLE "DB2INST1"."CRM_ZM_ORGAN_REF"  (
          "ORG_CODE" VARCHAR(32) NOT NULL , 
          "COM_ID" VARCHAR(30) NOT NULL , 
          "MREGIE_ID" VARCHAR(30) NOT NULL , 
          "CREGIE_ID" VARCHAR(30) NOT NULL )   
         IN "TD_SALE"   ;
ALTER TABLE "DB2INST1"."CRM_ZM_ORGAN_REF" 
    ADD PRIMARY KEY
        ("ORG_CODE") ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ORGAN_REF" TO USER "DB2INST1"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ORGAN_REF" TO USER "DB2INST2"  ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ORGAN_REF" TO USER "READER  "  ;

GRANT CONTROL ON TABLE "DB2INST1"."CRM_ZM_ORGAN_REF" TO USER "DB2INST1"  ;



INSERT INTO DB2INST1.CRM_ZM_ORGAN_REF
(ORG_CODE, COM_ID, MREGIE_ID, CREGIE_ID)
VALUES('10110101', '1011010211', '1011010212', '1011010212');

INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '05', '国有', '1401', '国有');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '09', '责令暂停', '1010', '责令停业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('NOW_EFFECT_STATUS', '客户状态', '03', '暂停', '2703', '暂停营业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '10', '暂停恢复', '1011', '责令停业恢复营业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '06', '集体', '1402', '集体');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '02', '五保户', '2403', '低保户');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '13', '取消', '1015', '听证');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '11', '撤回', '1013', '撤回');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('NOW_EFFECT_STATUS', '客户状态', '01', '新办', '2701', '初始申请');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('AREA_TYPE', '市场类型', 'X', '乡村', '3002', '乡村');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '07', '歇业', '1007', '歇业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '04', '有限责任', '1407', '有限责任');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '01', '残疾人', '2402', '残疾人');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '08', '股份有限公司', '1409', '股份有限公司');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'F', '娱乐服务业', '2906', '娱乐服务业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '01', '股份制（合作）', '1405', '股份制（合作）');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('NOW_EFFECT_STATUS', '客户状态', '04', '注销', '2705', '注销');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '06', '注销', '1009', '登记注销');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '07', '个体', '1403', '个体');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'B', '便利店', '2902', '便利店');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '03', '外商投资', '1408', '外商投资');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_CUST_BUSI_AREA_PART', '经营场所权属', '2', '租赁', '2503', '无偿使用');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '06', '注销', '1012', '审批注销');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_CUST_BUSI_AREA_PART', '经营场所权属', '2', '租赁', '2502', '租赁');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '06', '特困户', '2406', '特困户');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'Z', '食杂店', '2901', '食杂店');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_CUST_BUSI_AREA_PART', '经营场所权属', '2', '租赁', '2505', '无偿使用(长期)');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '01', '延续', '1003', '延续');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '13', '取消', '1018', '基础信息维护');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'Y', '烟酒商店', '2905', '烟酒商店');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '04', '下岗失业人员', '2404', '下岗失业人员');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '00', '新办', '1001', '新办');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '90', '其他特殊群体', '2408', '其他');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('CHARTER_SCOPE', '主营范围', '01', '卷烟', '1501', '卷烟');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '12', '撤销', '1014', '撤销');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '11', '其他', '1410', '其他');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'S', '超市', '2903', '超市');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '90', '其他特殊群体', '2407', '原零售户被拆迁');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('NOW_EFFECT_STATUS', '客户状态', '02', '有效', '2702', '正常经营');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '02', '变更', '1002', '变更');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'N', '商场', '2904', '商场');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_CUST_BUSI_AREA_PART', '经营场所权属', '1', '自有', '2501', '自有');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '11', '其他', '1404', '合伙');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '05', '恢复营业', '1005', '恢复营业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('CHARTER_SCOPE', '主营范围', '03', '罚没烟', '1504', '罚没烟');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '05', '军烈属', '2405', '军烈属');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_CUST_BUSI_AREA_PART', '经营场所权属', '2', '租赁', '2504', '租赁(长期)');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('NOW_EFFECT_STATUS', '客户状态', '04', '注销', '2706', '责令停业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('SPECIAL_PERSON_GROUP', '特殊群体', '00', '非特殊群体', '2401', '非特殊群体');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('ECO_TYPE', '企业性质', '11', '其他', '1406', '个人投资');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('LM_APPLY_APPLY_TYPE', '申请类型', '04', '停业', '1004', '停业');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('CHARTER_SCOPE', '主营范围', '02', '雪茄烟', '1502', '雪茄烟 ');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('BIZ_FORMAT', '经营业态', 'Q', '其他', '2907', '其他');
INSERT INTO DB2INST1.CRM_ZM_ENUM_REF
(DICT_ID, DICT_NAME, DICT_KEY, DICT_VALUE, ZM_DICT_KEY, ZM_DICT_VALUE)
VALUES('AREA_TYPE', '市场类型', 'C', '城镇', '3001', '城镇');