-----------------------------------------------
--DSL_CUST_RM 零售户信息(专卖相关)   北京需求
-----------------------------------------------
CREATE TABLE DSL_CUST_RM  (
		  BUSINESS_ID VARCHAR(30) NOT NULL PRIMARY KEY,
		  MSG_ID VARCHAR(30) NOT NULL ,
		  CUST_ID VARCHAR(30)  , 
		  LICENSE_CODE VARCHAR(30)  , 
		  CUST_NAME VARCHAR(30)  , 
		  COM_ID VARCHAR(30)  , 
		  CREGIE_ID VARCHAR(30)  , 
		  STATUS CHAR(2)  , 
		  LICE_STATUS CHAR(2)  , 
		  LICE_BORN_DATE CHAR(8) , 
		  LICE_AVAIL_DATE CHAR(8) , 
		  LICE_ISSUE_DATE CHAR(10) , 
		  MANAGER VARCHAR(50) , 
		  MANAGER_ID_CARD VARCHAR(18) , 
		  REG_FUND DECIMAL(18,2)  , 
		  MANAGER_TEL VARCHAR(40) , 
		  MANAGER_SEX VARCHAR(2) , 
		  BUSI_ADDR VARCHAR(200) , 
		  BUSI_ZIP VARCHAR(6) , 
		  MANAGER_NATIVE VARCHAR(50) , 
		  MANAGER_ID_ADDR VARCHAR(100) , 
		  MANAGER_HANDTEL VARCHAR(40) , 
		  EMAIL VARCHAR(40) , 
		  SPECIAL_TYPE VARCHAR(2) , 
		  BUSI_LICENSE_ID VARCHAR(50) , 
		  BUSI_LICENSE_START_DATE CHAR(8) , 
		  COM_CHARA CHAR(2) , 
		  CHARTER_SCOPE VARCHAR(10) , 
		  COR_EMP_AMT INTEGER  , 
		  ALL_BUSI_AREA DECIMAL(18,2)  , 
		  BUSI_LICENSE_AVAIL_DATE CHAR(8) , 
		  BUSI_AREA_PART CHAR(1) , 
		  BUSI_ADDR_BEGIN_DATE CHAR(8) , 
		  BUSI_ADDR_AVAIL_DATE CHAR(8) , 
		  SUPPLY_CATEGORY VARCHAR(2)  , 
		  GEOGRAPHY_ENVIRONMENT VARCHAR(2)  , 
		  ORDER_TEL VARCHAR(30) , 
		  WORK_PORT VARCHAR(2)  , 
		  BASE_TYPE VARCHAR(2)  , 
		  IS_SEFL_CUST VARCHAR(2)  , 
		  HARDSHIP_TYPE VARCHAR(2) , 
		  AREA_TYPE VARCHAR(20) , 
		  RUT_ID VARCHAR(30) , 
		  LONGITUDE DECIMAL(18,2)  , 
		  LATITUDE DECIMAL(18,2)  
		  )  IN TD_DATACENTER;
COMMENT ON TABLE DSL_CUST_RM IS '零售户信息（专卖相关）';
COMMENT ON COLUMN DSL_CUST_RM.BUSINESS_ID IS '业务主键';
COMMENT ON COLUMN DSL_CUST_RM.MSG_ID IS '日志ID';
COMMENT ON COLUMN DSL_CUST_RM.CREGIE_ID IS '县专卖局编码';
COMMENT ON COLUMN DSL_CUST_RM.STATUS IS '零售户状态：01:新增；02:有效；03:暂停；04:无效';
COMMENT ON COLUMN DSL_CUST_RM.LICE_STATUS IS '许可证状态：0，无效；1，有效；默认1';
COMMENT ON COLUMN DSL_CUST_RM.LICE_BORN_DATE IS '许可证开始日期';
COMMENT ON COLUMN DSL_CUST_RM.LICE_AVAIL_DATE IS '许可证结束日期';
COMMENT ON COLUMN DSL_CUST_RM.LICE_ISSUE_DATE IS '许可证发证日期';
COMMENT ON COLUMN DSL_CUST_RM.MANAGER_SEX IS '负责人性别0:女,1:男';
COMMENT ON COLUMN DSL_CUST_RM.COM_CHARA IS '企业性质：01:股份合作,02:合伙企业,03:外商企业,04:有限公司,05:国有企业,06:集体企业,07:个体商户,08:股份有限,09:个人独资';
COMMENT ON COLUMN DSL_CUST_RM.GEOGRAPHY_ENVIRONMENT IS '地理环境：00:繁华商业区,01:机场车站,02:主要街道,03:一般街道,04:城市居民区,05:农村居民区,06:旅游景区,07:校园医院,08:军队大院,09:其它';
COMMENT ON COLUMN DSL_CUST_RM.ORDER_TEL IS '是否烟草自营店  ';
COMMENT ON COLUMN DSL_CUST_RM.WORK_PORT IS '市场类型： C:城镇,X:乡村';
COMMENT ON COLUMN DSL_CUST_RM.BASE_TYPE IS '经营业态: Z:食杂店,B:便利店,S:超市,N:商场,Y:烟酒商店,F:娱乐服务,Q:其他';
COMMENT ON COLUMN DSL_CUST_RM.IS_SEFL_CUST IS '是否烟草自营店';
COMMENT ON COLUMN DSL_CUST_RM.HARDSHIP_TYPE IS '困难户类型';
COMMENT ON COLUMN DSL_CUST_RM.AREA_TYPE IS '商圈类型： 01:商业(集贸)区,02:工业区,03:学区,04:政务(商务)区,05:居民区(村),06:娱乐(旅游)区,07:旅客中转区,90:其他"';
COMMENT ON COLUMN DSL_CUST_RM.RUT_ID IS '网格';
COMMENT ON COLUMN DSL_CUST_RM.LONGITUDE IS '经度 ';
COMMENT ON COLUMN DSL_CUST_RM.LATITUDE IS '纬度';
-----------------------------------------------
--DSL_LICENSE 零售许可证信息   北京需求
-----------------------------------------------
CREATE TABLE
    DSL_LICENSE
    (
        MSG_ID VARCHAR(64),
        APPLE_TYPE VARCHAR(30),
        APPLY_DATE VARCHAR(30),
        APPLY_COMPLIET_DATE VARCHAR(30),
        LIC_NO VARCHAR(32),
        COMPANY_NAME VARCHAR(200),
        INDU_COMM_BUSINESS_LICENCE VARCHAR(30),
        MANAGER_NAME VARCHAR(60),
        IDCARD VARCHAR(30),
        BUSINESS_ADDR VARCHAR(200),
        IS_DIFFER_HOME_ADDR VARCHAR(30),
        SUPPLY_COMPANY VARCHAR(30),
        ACCREDI_DATE VARCHAR(30),
        VALIDATE_START VARCHAR(30),
        VALIDATE_END VARCHAR(30),
        DELIVERY_DATE VARCHAR(30),
        ISSUE_DATE VARCHAR(30),
        NOW_EFFECT_STATUS VARCHAR(35),
        LIC_ISSUING_ORG VARCHAR(200),
        MANAGER_SCOPE VARCHAR(30),
        GROUND_OWNERSHIP VARCHAR(30),
        LEASE_TIMELIMIT_START VARCHAR(30),
        LEASE_TIMELIMIT_END VARCHAR(30),
        IS_VALIDATE VARCHAR(30),
        ISSUE_ORG_CODE VARCHAR(32),
        RETAIL_CID_TYPE VARCHAR(35),
        RETAIL_CID_NO VARCHAR(35),
        RETAIL_CID_ADDRESS VARCHAR(200),
        RETAIL_ADDRESS VARCHAR(200),
        CONTRACT_PERSON VARCHAR(35),
        RETAIL_TEL VARCHAR(35),
        SPECIAL_PERSON_GROUP VARCHAR(30),
        BUSI_MGR_LIC_VALIDITY VARCHAR(30),
        BIZ_FORMAT VARCHAR(30),
        AREA_TYPE VARCHAR(30),
        ECO_TYPE VARCHAR(30),
        ECO_TYPE_OTHER VARCHAR(30),
        RLIC_ADC VARCHAR(30),
        CREATE_TIME VARCHAR(30),
        BIZ_AREA VARCHAR(30),
        IS_CHAIN VARCHAR(30),
        IS_MAIN VARCHAR(30),
        IS_BUSINESS VARCHAR(30),
        SPECIAL_GROUP_TYPE_OTHER VARCHAR(30),
        OLD_LIC_NO VARCHAR(50),
        SUPPLY_COMPANY_CODE VARCHAR(32),
        AGENT_NAME VARCHAR(60),
        AGENT_IDCARD VARCHAR(60),
        FIRST_ACCREDI_DATE VARCHAR(30),
        REGISTERED_CAPITAL VARCHAR(30),
        ORG_CODE VARCHAR(32),
        ORG_NAME VARCHAR(100),
        LAST_MODIFY_TIME VARCHAR(30),
        LAST_APPLY_TIME VARCHAR(30),
        LAST_OPERATE_COMPLETE_TIME VARCHAR(30),
        LAST_OPERATE_TYPE VARCHAR(30),
        LAST_OPERATE_NAME VARCHAR(50),
        LAST_OPERATE_LOGNAME VARCHAR(50),
        REMARK VARCHAR(1000),
        EXT1 VARCHAR(2000),
        EXT2 VARCHAR(2000)
    ) IN TD_DATACENTER;

